# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Download-Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 436)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.url_input = QtWidgets.QLineEdit(Dialog)
        self.url_input.setGeometry(QtCore.QRect(10, 30, 441, 25))
        self.url_input.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.url_input.setText("")
        self.url_input.setObjectName("url_input")
        self.add_button = QtWidgets.QPushButton(Dialog)
        self.add_button.setGeometry(QtCore.QRect(460, 30, 80, 25))
        self.add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_button.setObjectName("add_button")
        self.progress_output = QtWidgets.QTextEdit(Dialog)
        self.progress_output.setGeometry(QtCore.QRect(20, 279, 521, 151))
        self.progress_output.setObjectName("progress_output")
        self.url_list_widget = QtWidgets.QListWidget(Dialog)
        self.url_list_widget.setGeometry(QtCore.QRect(10, 60, 531, 91))
        self.url_list_widget.setObjectName("url_list_widget")
        self.progress_bar = QtWidgets.QProgressBar(Dialog)
        self.progress_bar.setGeometry(QtCore.QRect(10, 200, 531, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.download_button = QtWidgets.QPushButton(Dialog)
        self.download_button.setGeometry(QtCore.QRect(10, 160, 261, 25))
        self.download_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_button.setObjectName("download_button")
        self.pause_button = QtWidgets.QPushButton(Dialog)
        self.pause_button.setEnabled(False)
        self.pause_button.setGeometry(QtCore.QRect(460, 230, 80, 25))
        self.pause_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pause_button.setObjectName("pause_button")
        self.resume_button = QtWidgets.QPushButton(Dialog)
        self.resume_button.setEnabled(False)
        self.resume_button.setGeometry(QtCore.QRect(370, 230, 80, 25))
        self.resume_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor ))
        self.resume_button.setObjectName("resume_button")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(10, 230, 80, 25))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button.setObjectName("cancel_button")
        self.change_path_button = QtWidgets.QPushButton(Dialog)
        self.change_path_button.setGeometry(QtCore.QRect(280, 160, 261, 25))
        self.change_path_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_path_button.setObjectName("change_path_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_button.setText(_translate("Dialog", "add URL"))
        self.download_button.setText(_translate("Dialog", "Start Downloads"))
        self.pause_button.setText(_translate("Dialog", "Pause"))
        self.resume_button.setText(_translate("Dialog", "Resume"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.change_path_button.setText(_translate("Dialog", "Change Download Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
